name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    strategy:
      matrix:
        configuration: [Release]
        platform: [x64, x86, arm64]

    runs-on: windows-latest
    
    env:
      Solution_Name: Monaco.sln
      
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1
        
    - name: Restore dependencies
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
      
    - name: Version Visual Studio SDK projects
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        # The wildcard filter that identifies projects to version
        projectFilter: "**/Monaco.csproj"
        # Maps to the Version element
        version: 1.0.${{ github.run_number }}
        # Maps to the AssemblyVersion element
        assemblyVersion: 1.0.${{ github.run_number }}
        # Maps to the FileVersion element
        fileVersion: 1.0.${{ github.run_number }}
        # Maps to the InformationalVersion element
        informationalVersion: 1.0.${{ github.run_number }}
        
    # Create the app package by building and packaging the project
    - name: Create the app package
      run: msbuild -t:pack $env:Solution_Name /p:PackageVersion=1.0.${{ github.run_number }} /p:Configuration=$env:Configuration /p:Platform=$env:Platform  /p:AppxPackageDir="$env:Appx_Package_Dir"
      env:
        Appx_Package_Dir: Packages\
        Configuration: ${{ matrix.configuration }}
        Platform: ${{ matrix.platform }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
    
    - name: Publish
      run: dotnet nuget push **/*winui.monaco-editor*.nupkg --no-symbols --skip-duplicate --api-key ${{secrets.NUGET_API_KEY}} --source "nuget.org"
